export const SYMPTOM_LIST = [
  'Fever',
  'Cough',
  'Shortness of Breath',
  'Fatigue',
  'Muscle Aches',
  'Headache',
  'Sore Throat',
  'Loss of Taste or Smell',
  'Nausea',
  'Vomiting',
  'Diarrhea',
  'Chills',
  'Rash',
  'Dizziness',
  'Abdominal Pain',
  'Chest Pain',
  'Joint Pain',
  'Runny Nose',
  'Congestion',
  'Swelling',
];
