import React from 'react';

const AlertIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
    </svg>
);


const Disclaimer: React.FC = () => {
  return (
    <div className="bg-yellow-100 dark:bg-yellow-900/30 border-l-4 border-yellow-500 text-yellow-800 dark:text-yellow-200 p-4 rounded-lg mb-8 shadow-md" role="alert">
      <div className="flex">
        <div className="py-1">
            <AlertIcon />
        </div>
        <div className="ml-3">
          <p className="font-bold">Important Disclaimer</p>
          <p className="text-sm">This tool is for informational purposes only and does not constitute medical advice. The predictions are generated by a model and may not be accurate. Always consult a qualified healthcare professional for diagnosis and treatment.</p>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;